### ISSUE TITLE
-es.uri in deployment.yml not picked up with  prebuilt binary

### ISSUE THREAD

**Issue by helloravisha** [justwatchcom/elasticsearch_exporter#167] opened 2018-07-20 22:51 UTC
Hi Team,
 First of all, Thank you for providing elastic search exporter.  i am trying with prebuilt binary "elasticsearch_exporter-1.0.3rc1.linux-amd64.tar.gz" from the link,
https://github.com/justwatchcom/elasticsearch_exporter/releases .  tried changing -es.uri in deployment.yml , some how its always picking "localhost:9200", no matter what host i give.  Any inputs. 

Thanks ,
Ravi.

**Comment by zwopir** [comment] 2018-08-06 09:07
Hi @helloravisha,

I can't reproduce your issue. Can you give some context how you deployed the exporter?

**Comment by zwopir** [comment] 2018-08-17 13:54
closing this as I didn't get a reply. Don't hesitate to reopen if you encounter the problem

**Closed by zwopir** 2018-08-17 13:54 UTC
