### ISSUE TITLE
elasticsearch credentials exposed via metrics

### ISSUE THREAD

**Issue by lrstanley** [justwatchcom/elasticsearch_exporter#268] opened 2019-07-29 15:53 UTC
Similar to https://github.com/justwatchcom/elasticsearch_exporter/issues/188. elasticsearch credentials get exposed when you are using password authentication, and your username/password is configured in the `es.uri` command line flag. Loading this via environment variables wouldn't resolve this, as it's actually exposed as a metric, which means if your endpoint is unauthenticated for metrics, then this is completely exposed:

```
elasticsearch_clusterinfo_last_retrieval_failure_ts{url="https://<user>:<password>@myhostname.com:9200"} 1.564411951e+09
elasticsearch_clusterinfo_last_retrieval_success_ts{url="https://<user>:<password>@myhostname.com:9200"} 1.563386249e+09
elasticsearch_clusterinfo_up{url="https://<user>:<password>@myhostname.com:9200"} 0
```

Ideally, the best way to solve this would be to:

1. Have separate flags and/or environment variables for the username and password respectively. This way you can provide auth directly to the http client rather than just letting the client pull the credentials from the URL.
2. Or alternatively, one could do a regex string replacement on the URL to replace the password with something that's truncated.

**2** might be good to do regardless anyway, to ensure that people aren't accidentally exposing these credentials.

**Comment by lrstanley** [comment] 2019-07-29 16:11
I just now noticed the fixes in https://github.com/justwatchcom/elasticsearch_exporter/pull/264 -- when I searched that didn't come up. Can a release be pushed for this?

**Comment by lrstanley** [comment] 2019-07-29 16:11
Also tagging: https://github.com/justwatchcom/elasticsearch_exporter/issues/263

**Comment by zwopir** [comment] 2019-08-07 12:59
fixed in the new release: https://github.com/justwatchcom/elasticsearch_exporter/releases/tag/v1.1.0

**Closed by zwopir** 2019-08-07 12:59 UTC

**Comment by Shini31** [comment] 2021-02-16 15:08
The issue is still present in 1.1.0 release
```
elasticsearch_clusterinfo_last_retrieval_success_ts{url="https://<user>:<password>@myhostname.com:9200"} 1.613487671e+09
elasticsearch_exporter_build_info{branch="master",goversion="go1.12.3",revision="fe20e499ffdd6053e6153bac15eae494e08931df",version="1.1.0"} 1
```
